Issue:
  NodeID: OpexSoftware:UseCase:Application:Docker
  xmlns: http://www.arago.de/IssueSchema
  IssueSubject: 'Installing Docker Registry'
  DockerRegistryWorkflowHandlePKG:
    TargetApp: Docker
    TargetMachine: Zeeshan
    TargetState: Created
    User: zeeshan
    Host: 192.168.1.90
