Issue:
  NodeID: OpexSoftware:UseCase:Application:IptableFirewall
  xmlns: http://www.arago.de/IssueSchema
  IssueSubject: 'Configure a Iptables Based Firewall to accept a connection'
  ConfigureIptableBasedFirewallAcceptWorkflow: 
    TargetApp: IptableFirewall  
    TargetMachine: Zeeshan
    TargetState: Created
    ProtocolOfRule: tcp
    PortToAccept: 80
    User: zeeshan
    Host: 192.168.1.90