Issue:
  NodeID: OpexSoftware:UseCase:Application:Supervisor
  xmlns: http://www.arago.de/IssueSchema
  IssueSubject: 'Manage the state of a program or group of programs running via supervisord'
  SupervisorInstallConfig:
    TargetApp: Supervisor   
    TargetMachine: puja 
    TargetState: Created
    FilePath: /etc/supervisor/conf.d
    ProgramFile: /usr/local/bin/long.sh 
    FileName: long.conf
    Program: long
    User: puja
    Host: 192.168.1.86
   
